name: rbac
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
github: shokohara/haskell-rbac
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - App
  dependencies:
  - base >=4.7 && <5
  - aeson
  - aeson-casing
  - servant-server
  - text
  - monad-logger
  - transformers
  - wai-logger
  - HsOpenSSL
  - time ==1.6.0.1
  - wreq
  - http-client
  - http-client-tls
  - lens
  - lens-aeson
  - http-client-openssl
  - HDBC
  - HTTP
executables:
  rbac-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - rbac
    - wai-logger
    - servant-server
    - servant
    - wai
    - text
    - warp
tests:
  rbac-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - rbac
    - hspec
    - hspec-discover
    - hspec-wai
    - hspec-wai-json
    - aeson
    - http-types
    - bytestring
    - QuickCheck
    - quickcheck-text
